services:
  - type: web
    name: telegram-fantasy-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token
      - key: OPENROUTER_API_KEY
        value: your_openrouter_api_key
