services:
  - type: web
    name: fantasy-chatbot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
    autoDeploy: true
    region: oregon
    healthCheckPath: /
